add feature release 1.0.0

diff --git a/pipelines/.gitlab-ci.yml b/pipelines/.gitlab-ci.yml
--- a/pipelines/.gitlab-ci.yml
+++ b/pipelines/.gitlab-ci.yml
@@ -12,9 +12,9 @@ variables:
 
 workflow:
   rules:
-    - if: $CI_PIPELINE_SOURCE == "web"
+    - if: $CI_COMMIT_TAG
       when: always
-    - if: $CI_COMMIT_BRANCH == "main"
+    - if: $CI_PIPELINE_SOURCE == "web"
       when: always
     - when: never
 
@@ -35,14 +35,17 @@ build-app:
     - echo "$GITLAB_TOKEN" | docker login $GITLAB_REGISTRY -u $GITLAB_USERNAME --password-stdin
   script:
     - |
-      if [ "$CI_PIPELINE_SOURCE" == "web" ]; then
+      if [ -n "$CI_COMMIT_TAG" ]; then
+        echo "Building from tag: $CI_COMMIT_TAG"
+        BUILD_TAG=$CI_COMMIT_TAG
+      elif [ "$CI_PIPELINE_SOURCE" == "web" ]; then
         echo "Building from manual trigger: Branch=$BRANCH, Tag=$TAG"
         git fetch origin $BRANCH
         git checkout $BRANCH
         BUILD_TAG=$TAG
       else
-        echo "Building from automatic trigger: Branch=$CI_COMMIT_BRANCH"
-        BUILD_TAG=$CI_COMMIT_SHORT_SHA
+        echo "❌ Error: This pipeline only supports Tags or Manual triggers."
+        exit 1
       fi
     - |
       echo "Build app to docker image"
